GET http://localhost:5001/ads

###

GET http://localhost:5001/ads/12

###

POST http://localhost:5001/ads
Content-Type: application/json

  {
    "title": "Peugeot 208",
    "description":
      "Peugeot 208 jaune en bon état",
    "owner": "peugeot.seller@gmail.com",
    "price": 10000,
    "location": "Bordeaux",
    "category": 2,
    "tags": [1,2]
  }

###

DELETE http://localhost:5001/ads/11

###

PUT http://localhost:5001/ads/11
Content-Type: application/json

  {
    "title": "Bike to sell",
    "description":
      "My bike is purple and working fine.",
    "owner": "bike.seller@gmail.com",
    "price": 200,
    "location": "Lyon",
    "category": 1,
    "tags": [1]
  }

